export enum ErrorCode {
  // Authentication & Authorization (40x)
  AUTH_INVALID_CREDENTIALS = 'ERR_AUTH_001',
  AUTH_TOKEN_EXPIRED = 'ERR_AUTH_002',
  AUTH_UNAUTHORIZED = 'ERR_AUTH_003',
  AUTH_FORBIDDEN = 'ERR_AUTH_004',
  AUTH_REFRESH_TOKEN_INVALID = 'ERR_AUTH_005',
  AUTH_REFRESH_TOKEN_EXPIRED = 'ERR_AUTH_006',

  // Users (40x)
  USER_NOT_FOUND = 'ERR_USER_001',
  USER_CONFLICT = 'ERR_USER_002',
  USER_CREATE_FAILED = 'ERR_USER_003',
  USER_UPDATE_FAILED = 'ERR_USER_004',
  USER_DELETE_FAILED = 'ERR_USER_005',

  // Consultations (40x)
  CONSULTATION_NOT_FOUND = 'ERR_CONSULT_001',
  CONSULTATION_CREATE_FAILED = 'ERR_CONSULT_002',

  // AI/Chat (50x)
  AI_SERVICE_ERROR = 'ERR_AI_001',
  AI_TIMEOUT = 'ERR_AI_002',
  AI_RATE_LIMITED = 'ERR_AI_003',
  AI_UNAVAILABLE = 'ERR_AI_004',
  AI_PARSE_FAILED = 'ERR_AI_005',
  CHAT_MESSAGE_FAILED = 'ERR_CHAT_001',
  CHAT_NOT_FOUND = 'ERR_CHAT_002',

  // Database (50x)
  DATABASE_ERROR = 'ERR_DATABASE_001',
  DATABASE_CONSTRAINT = 'ERR_DATABASE_002',

  // Validation (40x)
  VALIDATION_ERROR = 'ERR_VALIDATION_001',

  // System (50x)
  INTERNAL_ERROR = 'ERR_INTERNAL_001',
  SERVICE_UNAVAILABLE = 'ERR_SERVICE_UNAVAILABLE_001',

  // Generic / Routing (40x)
  RESOURCE_NOT_FOUND = 'ERR_RESOURCE_001',
}
